nodeLinker: pnpm

packageExtensions:
  "@storybook/builder-webpack5@^7.3.1":
    dependencies:
      "@storybook/components": "^7.3.1"
      "@storybook/manager-api": "^7.3.1"
    peerDependencies:
      react: "^16.8.0 || ^17.0.0 || ^18.0.0"
      react-dom: "^16.8.0 || ^17.0.0 || ^18.0.0"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
