//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "emoji")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::local_file::Entity")]
    LocalFile,
}

impl Related<super::local_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocalFile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
